require 'rake'
require 'rake/testtask'

task :default => [:test_akka]

desc "Run tests for basic Akka framework"
Rake::TestTask.new("test_akka") { |t|
  t.pattern = 'tests/*_test.rb'
  t.verbose = true
  t.warning = true
  t.options = ["akka"]
}

desc "Run tests for basic Akka framework"
Rake::TestTask.new("test_akka_nb") { |t|
  t.pattern = 'tests/*_test.rb'
  t.verbose = true
  t.warning = true
  t.options = ["akka_nb"]
}